# Generated by Django 2.1.3 on 2018-11-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
